CREATE TABLE events (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source          TEXT        NOT NULL,
  external_id     TEXT        NOT NULL,
  kind            TEXT        NOT NULL,
  payload         JSONB       NOT NULL,
  salience        INTEGER,
  triaged_at      TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- How many tier-1 batches this event has been submitted to and come back
  -- from unscored. After TRIAGE_MAX_ATTEMPTS it is given up on.
  triage_attempts INTEGER     NOT NULL DEFAULT 0,
  -- Set when triage gave up. `triaged_at` is stamped with it and `salience`
  -- stays NULL, which is how an abandoned event is told apart from a scored
  -- one: it is out of the scan window but it did not silently become a zero.
  triage_error    TEXT,
  UNIQUE (source, external_id)
);
CREATE INDEX events_untriaged ON events (triaged_at, triage_attempts, id);
CREATE INDEX events_kind      ON events (kind);

CREATE TABLE actions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector   TEXT        NOT NULL,
  tool        TEXT        NOT NULL,
  args        JSONB       NOT NULL,
  preview     TEXT        NOT NULL,
  rationale   TEXT        NOT NULL,
  status      TEXT        NOT NULL
              CONSTRAINT actions_status_check CHECK (status IN
                ('proposed','approved','rejected','expired','executed','failed')),
  reason      TEXT,
  result      TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at  TIMESTAMPTZ NOT NULL,
  decided_at  TIMESTAMPTZ,
  executed_at TIMESTAMPTZ
);
CREATE INDEX actions_status ON actions (status);

CREATE TABLE conversations (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claude_session TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE messages (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT      NOT NULL REFERENCES conversations (id),
  role            TEXT        NOT NULL,
  surface         TEXT        NOT NULL,
  body            TEXT        NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX messages_conversation ON messages (conversation_id, id);

CREATE TABLE facts (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic      TEXT        NOT NULL,
  body       TEXT        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Set when `remember` overwrote the body of an existing topic; NULL on a
  -- fact nobody has corrected.
  updated_at TIMESTAMPTZ
);
-- Not in the SQLite schema. It makes `remember` a single upsert and closes
-- the duplicate-topic case the old code worked around by taking the lowest id.
CREATE UNIQUE INDEX facts_topic_lower ON facts (lower(topic));

CREATE TABLE runs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind        TEXT        NOT NULL,
  prompt      TEXT        NOT NULL,
  outcome     TEXT        NOT NULL,
  detail      TEXT,
  action_ids  JSONB       NOT NULL DEFAULT '[]'::jsonb,
  cost_usd    DOUBLE PRECISION,
  duration_ms BIGINT,
  started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ
);
CREATE INDEX runs_started ON runs (started_at);

CREATE TABLE schedules (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT        NOT NULL UNIQUE,
  cron        TEXT        NOT NULL,
  enabled     BOOLEAN     NOT NULL DEFAULT TRUE,
  last_run_at TIMESTAMPTZ
);

CREATE TABLE kv (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
