CREATE TABLE claude_sessions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   TEXT        NOT NULL UNIQUE,
  cwd          TEXT        NOT NULL,
  git_branch   TEXT,
  reason       TEXT        NOT NULL,
  status       TEXT        NOT NULL DEFAULT 'pending',  -- pending | done | skipped | failed
  summary      TEXT,
  transcript   TEXT,        -- user and assistant text only, capped
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  search       tsvector GENERATED ALWAYS AS (
                 setweight(to_tsvector('simple', coalesce(summary, '')), 'A') ||
                 setweight(to_tsvector('simple', coalesce(transcript, '')), 'B')
               ) STORED
);
CREATE INDEX claude_sessions_cwd_created ON claude_sessions (cwd, created_at DESC);
CREATE INDEX claude_sessions_search ON claude_sessions USING GIN (search);

-- One-off copy from the old Python-hook schema, if this database has it.
DO $$
BEGIN
  IF to_regclass('claude_code.session_summaries') IS NOT NULL THEN
    INSERT INTO claude_sessions
      (session_id, cwd, git_branch, reason, status, summary, created_at, updated_at)
    SELECT DISTINCT ON (session_id)
      session_id, cwd, git_branch, reason, status, summary, created_at, updated_at
    FROM claude_code.session_summaries
    WHERE session_id <> ''
    ORDER BY session_id, id DESC
    ON CONFLICT (session_id) DO NOTHING;
    DROP SCHEMA claude_code CASCADE;
  END IF;
END
$$;
